app:
  myport: ${PORT:0}
spring:
  application:
    name: promocao-service
  datasource:
    url: jdbc:h2:mem:promocao
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: ${app.myport}
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    propagation:
      type: w3c
    sampling:
      probability: 1
openapi:
  service:
    title: promocao doc
    version: 1.0.0
    url: http://localhost:9098
springdoc:
  api-docs:
    path: /promocao/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html