spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: pedido
          uri: lb://PEDIDO-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/pedido/**
        - id: produto
          uri: lb://PRODUTO-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/produto/**
        - id: promocao
          uri: lb://PROMOCAO-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/promocao/**
eureka:
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka
server:
  port: 9098
