app:
  myport: ${PORT:0}
spring:
  application:
    name: pedido-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pedido
server:
  port: ${app.myport}
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

