app:
  myport: ${PORT:0}
spring:
  application:
    name: pedido-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pedido
server:
  port: ${app.myport}
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    propagation:
      type: w3c
    sampling:
      probability: 1
openapi:
  service:
    title: pedido doc
    version: 1.0.0
    url: http://localhost:9098
springdoc:
  api-docs:
    path: /pedido/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
